# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

max_flow_sufficient <- function(delta_in) {
    .Call(`_econometric_factor_identification_max_flow_sufficient_r`, delta_in)
}

variance_is_identified_indicator <- function(delta_in) {
    .Call(`_econometric_factor_identification_counting_rule_holds_r`, delta_in)
}

max_flow_necessary <- function(delta_in) {
    .Call(`_econometric_factor_identification_max_flow_necessary_r`, delta_in)
}

variance_may_be_identified_indicator <- function(delta_in) {
    .Call(`_econometric_factor_identification_necessary_condition_holds_r`, delta_in)
}

